name = "randomModpack"
author = "xrez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37bc8ee2a6d0fd79827067d3c67f9b8ec7f9d8b52e85d969e11fac058b95db87"

[versions]
forge = "47.2.8"
minecraft = "1.20.1"
