name = "randomModpack"
author = "xrez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de91ba1fa999fe6f2dd521cc0c06b42731ae6c1d0d26d7754dd812b1e9971ce3"

[versions]
forge = "47.2.8"
minecraft = "1.20.1"
